### ISSUE TITLE
Files are copied to target without package folders tree

### ISSUE THREAD

**Issue by erezul** [imyuyu/FileSyncPlugin#2] opened 2024-01-18 09:07 UTC
I'm using v. 1.15 on IntelliJ IDEA 2023.3.2 (Ultimate Edition)
Build #IU-233.13135.103, built on December 20, 2023
I tried to synch and got the class file only.
I changed the configuration to use false on ‘Delete obsolete files/dir’ and the next time package folders tree was created.
However, the next time the files were copied outside the package folders tree...

**Comment by imyuyu** [comment] 2024-01-19 08:05
hi

Thank you for your report. I will try to reproduce it later. Or can you provide a minimum usable example?

**Comment by erezul** [comment] 2024-01-19 10:49
Sure,
I used to use the old File Synchronizer till it stopped working on newer IDEA.
Then I found the new File Synch which seems similar.
However, the first time I used it, it did not create the packages folders and placed the class files directly under the target folder.
Then I tried with false for ‘Delete obsolete files/dir’.
Seems the behavior is not stable and not related to this flag.
Sometimes it created the package folders tree and sometimes it does not.
I use IntelliJ IDEA 2023.3.2 (Ultimate Edition)

Here are my setup instructions for my team:
install and restart
[A black background with white text  Description automatically generated]
Configure under Settings > Tools > File Synch
[A screenshot of a computer  Description automatically generated]
NOTE:
Be sure to use false on ‘Delete obsolete files/dir’ or class files will be copied without their package folders.

Close IDEA
Open .idea\workspace.xml
Manually add all the configuration:
  <component name="FileSync">
    <option name="targetMappings">
      <list>
        <TargetMappings>
          <option name="name" value="Default" />
          <option name="synchroMappings">
            <array>
              <SynchroMapping>
                <option name="srcPath" value="$PROJECT_DIR$/../application/target/classes/" />
                <option name="destPath" value="$PROJECT_DIR$/../../deploy/jbs/echos.ear/lib/1classes.jar/" />
              </SynchroMapping>
              ...
              <SynchroMapping>
                <option name="srcPath" value="$PROJECT_DIR$/../models/system/target/classes/" />
                <option name="destPath" value="$PROJECT_DIR$/../../deploy/jbs/echos.ear/lib/1classes.jar/" />
              </SynchroMapping>
            </array>
          </option>
        </TargetMappings>
      </list>
    </option>
  </component>
Open IDEA and test.
On compiled java class right click and synchronize:
[A blue and black rectangular object  Description automatically generated]

Classes and their packages folders will be copied under deploy\jbs\echos.ear\lib\1classes.jar\
[A screen shot of a computer  Description automatically generated]
Then all you need to do is restart ECHOS.

Thanks,
Erez

**Comment by imyuyu** [comment] 2024-04-26 13:22
hi

I am unable to reproduce it and currently do not have time for further analysis, so I am closing this issue.

**Closed as completed by imyuyu** 2024-04-26 13:22 UTC
